export const PHRASES = [
  "¡Punta Cana nos espera! El mar turquesa se siente cada vez más cerca. 🌊",
  "Menos estrés, más piña colada. 🍹",
  "Tu único deber hoy es soñar con la arena blanca. ✨",
  "Armá la valija mental: la felicidad está en camino. 🧳",
  "Punta Cana es el destino, el disfrute es el viaje. ☀️",
  "Recordá: te merecés este descanso más que nadie.",
  "Playa, sol y amigos... ¿Qué más se puede pedir?",
  "El Caribe tiene tu nombre escrito en la arena.",
  "Contando los segundos para el primer chapuzón. 🏊",
  "La vida es corta, comprate el viaje. ✈️",
  "El paraíso no es un lugar, es un estado mental (¡y queda en Punta Cana!).",
  "Que el viento caribeño se lleve todas tus preocupaciones.",
  "Preparando los lentes de sol y la mejor energía. 😎",
  "Días de sol, noches de estrellas y recuerdos para toda la vida.",
  "¡Alerta de viaje! Punta Cana está llamando.",
  "Un viaje se vive tres veces: al soñarlo, al vivirlo y al recordarlo.",
  "La felicidad viene en olas. 🌊",
  "Falta menos para el brindis frente al mar.",
  "Bronceado de piel, paz en el alma.",
  "Dejá que el mar te cure todo. 💙",
  "Punta Cana: donde el tiempo se detiene y empieza el relax.",
  "No cuentes los días, haz que los días cuenten.",
  "Próxima parada: ¡El Paraíso!",
  "El agua es más clara y la vida es más dulce en el Caribe.",
  "Desconexión total activada en 3, 2, 1...",
  "¡A romper la rutina bajo las palmeras! 🌴",
  "Viajar es lo único que compras y te hace más rico.",
  "¡Preparen esos pasaportes!",
  "Que empiece la cuenta regresiva hacia las mejores vacaciones.",
  "Un brindis por los momentos que nos quitan el aliento.",
  "La arena en los pies limpia cualquier mala vibra.",
  "Donde hay sol, hay alegría.",
  "No es un viaje cualquiera, es NUESTRO viaje. 🥂",
  "Punta Cana: el remedio para el alma.",
  "Sol, playa y mucha diversión... ¡allá vamos!",
  "Todo lo bueno empieza con una sonrisa y un pasaje de avión.",
  "Dejá que las olas marquen el ritmo de tus días.",
  "Vitamin Sea: exactamente lo que el médico recetó. 🩺🌊",
  "Cambiando el despertador por el sonido del mar.",
  "Haciendo espacio para los mejores recuerdos del 2026.",
  "Punta Cana no es un sueño, ¡es una promesa!",
  "¡Salud por las aventuras que están por comenzar! 🍹",
  "Un descanso bien merecido para recargar energías.",
  "Donde el cielo se junta con el mar turquesa.",
  "¡Que la única prisa sea llegar a la playa!",
  "Preparate para el modo avión definitivo. ✈️📴",
  "Risas, sol y el mejor grupo de viaje del mundo.",
  "Una escapada perfecta para gente espectacular.",
  "Punta Cana: ¡La cuenta regresiva es real!",
  "El paraíso nos está guardando una reposera. 🏖️",
  "El sol brilla más fuerte cuando estás de vacaciones.",
  "Que la arena sea tu único suelo durante una semana.",
  "La vida se ve mejor a través de unas gafas de sol.",
  "Un viaje inolvidable se construye con grandes momentos.",
  "¡Ponete el protector solar, nos vamos al Caribe!",
  "La felicidad tiene aroma a coco y brisa marina.",
  "Pronto estaremos bailando bajo las estrellas.",
  "Que tu única preocupación sea qué trago pedir.",
  "Punta Cana: donde las penas se ahogan en agua salada.",
  "El Caribe te espera con los brazos abiertos.",
  "Colecciona momentos, no cosas.",
  "Un pasaporte lleno de sellos y un corazón lleno de historias.",
  "¡Listos para crear recuerdos imborrables!",
  "Que la brisa del mar te despeine el alma.",
  "¡El viaje de nuestras vidas está a la vuelta de la esquina!",
  "Punta Cana es sinónimo de pura vida.",
  "Cargando baterías caribeñas... 🔋☀️",
  "Una semana de puro disfrute sin mirar el reloj.",
  "Preparate para la sobredosis de mar turquesa.",
  "Punta Cana nos llama y tenemos que ir.",
  "La aventura está ahí afuera, ¡vamos a buscarla!",
  "¡A sacarle chispas a esas vacaciones!",
  "Que la única sombra en tu día sea la de una palmera.",
  "La felicidad se mide en kilómetros de playa.",
  "Un viaje al Caribe sana el cuerpo y la mente.",
  "Cambiando el frío de la rutina por el calor caribeño.",
  "Punta Cana nos regalará los mejores atardeceres.",
  "El paraíso existe y vamos hacia él.",
  "¡Menos pantallas y más olas!",
  "Que la música del mar sea tu banda sonora.",
  "¡A vivir cada segundo al máximo!",
  "Un viaje increíble se planea con el corazón.",
  "Punta Cana: el descanso que tu cuerpo te pide.",
  "¡Arriba ese ánimo caribeño!",
  "Preparados para la desconexión total.",
  "Un brindis por los días dorados que se vienen.",
  "Punta Cana: risas garantizadas.",
  "Que la brisa caribeña limpie tu mente.",
  "El Caribe es el lugar donde los sueños se hacen realidad.",
  "Punta Cana: el viaje que estabas esperando.",
  "¡A disfrutar como si no hubiera un mañana!",
  "La cuenta regresiva más emocionante de todas.",
  "Que el mar te susurre sus secretos de calma.",
  "Punta Cana: tu oasis personal.",
  "¡Todo listo para la gran aventura caribeña!",
  "La vida es mejor en sandalias.",
  "Un viaje espectacular para un grupo espectacular.",
  "Punta Cana: ¡vamos por esos recuerdos!",
  "La magia del Caribe te atrapará por completo.",
  "¡Nos vemos en Punta Cana!"
];
